name: Terraform fmt
on: [push, pull_request]
jobs:
  terrafmt:
    name: terrafmt
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check out terrafmt code
        uses: actions/checkout@v2
        with:
          repository: jeremmfr/terrafmt
          ref: support-return-back-quote
          path: terrafmt
      - name: Build terrafmt bin
        run: cd terrafmt && go install ./... && cd ${GITHUB_WORKSPACE}
      - name: Terrafmt diff on html.markdown
        run: find . | egrep "html.markdown" | sort | while read f; do terrafmt diff $f; done >> /tmp/results.html.markdown
      - name: Terrafmt diff on _test.go
        run: find . | egrep "_test.go" | sort | while read f; do terrafmt diff $f; done >> /tmp/results.test.go
      - name: Generate error if results not empty
        run: |
          if [[ -s /tmp/results.html.markdown || -s /tmp/results.test.go ]] ; then 
            cat /tmp/results.html.markdown
            cat /tmp/results.test.go
            echo "terraform blocks in website/test-go files not being properly formatted"
            exit 1
          fi